//Each new term in the Fibonacci sequence is generated by adding the 
//previous two terms. By starting with 1 and 2, 
//the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

alert(problem2(4000000));

function problem2(input){

var sum = 0;
var a = 0;
var b = 1;
var fib = 1;
while(fib <= input){
    fib = a + b;
    a = b;
    b = fib;
	if((fib & 1) == 0)
		{
    sum += fib
		}
	}

return sum;
    
}